// <auto-generated />
using System;
using IRasRag.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IRasRag.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130150138_AddCoreEntities")]
    partial class AddCoreEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IRasRag.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("FarmingBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("farming_batch_id");

                    b.Property<Guid>("FishTankId")
                        .HasColumnType("uuid")
                        .HasColumnName("fish_tank_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("SensorLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_log_id");

                    b.Property<Guid>("SensorTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_type_id");

                    b.Property<Guid>("SpeciesThresholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_threshold_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<float>("Value")
                        .HasColumnType("real")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("SensorTypeId")
                        .HasDatabaseName("ix_alerts_sensor_type_id");

                    b.HasIndex("SpeciesThresholdId")
                        .HasDatabaseName("ix_alerts_species_threshold_id");

                    b.HasIndex("FarmingBatchId", "Status")
                        .HasDatabaseName("ix_alerts_farming_batch_id_status");

                    b.HasIndex("FishTankId", "Status")
                        .HasDatabaseName("ix_alerts_fish_tank_id_status");

                    b.HasIndex("SensorLogId", "Status")
                        .HasDatabaseName("ix_alerts_sensor_log_id_status");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Camera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_cameras");

                    b.HasIndex("FarmId")
                        .HasDatabaseName("ix_cameras_farm_id");

                    b.ToTable("cameras", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.ControlDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommandOff")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("command_off");

                    b.Property<string>("CommandOn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("command_on");

                    b.Property<Guid>("ControlDeviceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("control_device_type_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("MasterBoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_board_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("PinCode")
                        .HasColumnType("integer")
                        .HasColumnName("pin_code");

                    b.Property<bool>("State")
                        .HasColumnType("boolean")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_control_devices");

                    b.HasIndex("ControlDeviceTypeId")
                        .HasDatabaseName("ix_control_devices_control_device_type_id");

                    b.HasIndex("MasterBoardId", "IsDeleted")
                        .HasDatabaseName("ix_control_devices_master_board_id_is_deleted");

                    b.HasIndex("MasterBoardId", "PinCode")
                        .IsUnique()
                        .HasDatabaseName("ix_control_devices_master_board_id_pin_code");

                    b.ToTable("control_devices", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.ControlDeviceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_control_device_types");

                    b.ToTable("control_device_types", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.CorrectiveAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("action_taken");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_corrective_actions");

                    b.HasIndex("AlertId")
                        .HasDatabaseName("ix_corrective_actions_alert_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_corrective_actions_user_id");

                    b.ToTable("corrective_actions", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_documents_uploaded_by_user_id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_farms");

                    b.ToTable("farms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            Address = "Đường 123, Tp.HCM",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "contact@aquabluefarm.vn",
                            IsDeleted = false,
                            Name = "Trang trại RAS mẫu",
                            PhoneNumber = "+84-123-456-789"
                        });
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.FarmingBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualHarvestDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_harvest_date");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<float>("CurrentQuantity")
                        .HasColumnType("real")
                        .HasColumnName("current_quantity");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EstimatedHarvestDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("estimated_harvest_date");

                    b.Property<Guid>("FishTankId")
                        .HasColumnType("uuid")
                        .HasColumnName("fish_tank_id");

                    b.Property<float>("InitialQuantity")
                        .HasColumnType("real")
                        .HasColumnName("initial_quantity");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("Id")
                        .HasName("pk_farming_batches");

                    b.HasIndex("FishTankId")
                        .HasDatabaseName("ix_farming_batches_fish_tank_id");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("ix_farming_batches_species_id");

                    b.ToTable("farming_batches", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.FeedType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("manufacturer");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<float>("ProteinPercentage")
                        .HasColumnType("real")
                        .HasColumnName("protein_percentage");

                    b.Property<float>("WeightPerUnit")
                        .HasColumnType("real")
                        .HasColumnName("weight_per_unit");

                    b.HasKey("Id")
                        .HasName("pk_feed_types");

                    b.ToTable("feed_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000201"),
                            Description = "Thức ăn có hàm lượng protein cao, phù hợp cho giai đoạn đầu phát triển của cá.",
                            Manufacturer = "AquaFeed Solutions",
                            Name = "Giàu protein",
                            ProteinPercentage = 45f,
                            WeightPerUnit = 25f
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000202"),
                            Description = "Thức ăn tiêu chuẩn, phù hợp cho giai đoạn phát triển tiếp theo của cá.",
                            Manufacturer = "AquaFeed Solutions",
                            Name = "Tiêu chuẩn",
                            ProteinPercentage = 38f,
                            WeightPerUnit = 25f
                        });
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.FeedingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float>("Amount")
                        .HasColumnType("real")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FarmingBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("farming_batch_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_feeding_logs");

                    b.HasIndex("FarmingBatchId", "CreatedDate")
                        .HasDatabaseName("ix_feeding_logs_farming_batch_id_created_date");

                    b.ToTable("feeding_logs", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.FishTank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CameraUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("camera_url");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<float>("Height")
                        .HasColumnType("real")
                        .HasColumnName("height");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<float>("Radius")
                        .HasColumnType("real")
                        .HasColumnName("radius");

                    b.Property<string>("TopicCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("topic_code");

                    b.HasKey("Id")
                        .HasName("pk_fish_tanks");

                    b.HasIndex("FarmId", "IsDeleted")
                        .HasDatabaseName("ix_fish_tanks_farm_id_is_deleted");

                    b.ToTable("fish_tanks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000301"),
                            CameraUrl = "",
                            FarmId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            Height = 0f,
                            IsDeleted = false,
                            Name = "Bể nuôi số 1",
                            Radius = 0f,
                            TopicCode = "tank/001"
                        });
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.GrowthStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_growth_stages");

                    b.ToTable("growth_stages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000401"),
                            Description = "Giai đoạn từ khi nở đến khi cá phát triển đủ lớn để chuyển sang giai đoạn cá giống.",
                            Name = "Cá bột"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000402"),
                            Description = "Giai đoạn từ cá bột đến khi cá đạt kích thước thương phẩm.",
                            Name = "Cá giống"
                        });
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DefaultState")
                        .HasColumnType("boolean")
                        .HasColumnName("default_state");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<string>("ExecutionDays")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("execution_days");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_type_id");

                    b.Property<float?>("MaxValue")
                        .HasColumnType("real")
                        .HasColumnName("max_value");

                    b.Property<float?>("MinValue")
                        .HasColumnType("real")
                        .HasColumnName("min_value");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("RepeatIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("repeat_interval_minutes");

                    b.Property<Guid?>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("JobTypeId")
                        .HasDatabaseName("ix_jobs_job_type_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_jobs_sensor_id");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.JobControlMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ControlDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("control_device_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<bool>("TargetState")
                        .HasColumnType("boolean")
                        .HasColumnName("target_state");

                    b.Property<string>("TriggerCondition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trigger_condition");

                    b.HasKey("Id")
                        .HasName("pk_job_control_mappings");

                    b.HasIndex("ControlDeviceId")
                        .HasDatabaseName("ix_job_control_mappings_control_device_id");

                    b.HasIndex("JobId", "ControlDeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_job_control_mappings_job_id_control_device_id");

                    b.ToTable("job_control_mappings", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.JobType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_job_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_job_types_name");

                    b.ToTable("job_types", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.MasterBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FishTankId")
                        .HasColumnType("uuid")
                        .HasColumnName("fish_tank_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mac_address");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_master_boards");

                    b.HasIndex("MacAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_master_boards_mac_address");

                    b.HasIndex("FishTankId", "IsDeleted")
                        .HasDatabaseName("ix_master_boards_fish_tank_id_is_deleted");

                    b.ToTable("master_boards", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.MortalityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<float>("Quantity")
                        .HasColumnType("real")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_mortality_logs");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_mortality_logs_batch_id");

                    b.ToTable("mortality_logs", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("SuggestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("suggestion_text");

                    b.HasKey("Id")
                        .HasName("pk_recommendations");

                    b.HasIndex("AlertId")
                        .HasDatabaseName("ix_recommendations_alert_id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_recommendations_document_id");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_date");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("MasterBoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_board_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("PinCode")
                        .HasColumnType("integer")
                        .HasColumnName("pin_code");

                    b.Property<Guid>("SensorTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_type_id");

                    b.HasKey("Id")
                        .HasName("pk_sensors");

                    b.HasIndex("SensorTypeId")
                        .HasDatabaseName("ix_sensors_sensor_type_id");

                    b.HasIndex("MasterBoardId", "IsDeleted")
                        .HasDatabaseName("ix_sensors_master_board_id_is_deleted");

                    b.HasIndex("MasterBoardId", "PinCode")
                        .IsUnique()
                        .HasDatabaseName("ix_sensors_master_board_id_pin_code");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.SensorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Data")
                        .HasColumnType("double precision")
                        .HasColumnName("data");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("data_json");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsWarning")
                        .HasColumnType("boolean")
                        .HasColumnName("is_warning");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.HasKey("Id")
                        .HasName("pk_sensor_logs");

                    b.HasIndex("SensorId", "CreatedAt")
                        .HasDatabaseName("ix_sensor_logs_sensor_id_created_at");

                    b.ToTable("sensor_logs", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.SensorType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("MeasureType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("measure_type");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("Id")
                        .HasName("pk_sensor_types");

                    b.ToTable("sensor_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0000-000000000001"),
                            MeasureType = "Nhiệt độ",
                            Name = "Nhiệt độ nước",
                            UnitOfMeasure = "Độ C"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0000-000000000002"),
                            MeasureType = "Tính axit",
                            Name = "Độ pH",
                            UnitOfMeasure = "pH"
                        });
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_species");

                    b.ToTable("species", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000101"),
                            Name = "Cá rô phi"
                        });
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.SpeciesStageConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float>("AmountPer100Fish")
                        .HasColumnType("real")
                        .HasColumnName("amount_per100fish");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("ExpectedDurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("expected_duration_days");

                    b.Property<Guid>("FeedTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("feed_type_id");

                    b.Property<int>("FrequencyPerDay")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_per_day");

                    b.Property<Guid>("GrowthStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("growth_stage_id");

                    b.Property<float?>("MaxStockingDensity")
                        .HasColumnType("real")
                        .HasColumnName("max_stocking_density");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.HasKey("Id")
                        .HasName("pk_species_stage_configs");

                    b.HasIndex("FeedTypeId")
                        .HasDatabaseName("ix_species_stage_configs_feed_type_id");

                    b.HasIndex("GrowthStageId")
                        .HasDatabaseName("ix_species_stage_configs_growth_stage_id");

                    b.HasIndex("SpeciesId", "GrowthStageId")
                        .IsUnique()
                        .HasDatabaseName("ix_species_stage_configs_species_id_growth_stage_id");

                    b.ToTable("species_stage_configs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000601"),
                            AmountPer100Fish = 0.5f,
                            ExpectedDurationDays = 30,
                            FeedTypeId = new Guid("aaaaaaaa-0000-0000-0000-000000000201"),
                            FrequencyPerDay = 6,
                            GrowthStageId = new Guid("aaaaaaaa-0000-0000-0000-000000000401"),
                            MaxStockingDensity = 50f,
                            SpeciesId = new Guid("aaaaaaaa-0000-0000-0000-000000000101")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000602"),
                            AmountPer100Fish = 3f,
                            ExpectedDurationDays = 90,
                            FeedTypeId = new Guid("aaaaaaaa-0000-0000-0000-000000000202"),
                            FrequencyPerDay = 3,
                            GrowthStageId = new Guid("aaaaaaaa-0000-0000-0000-000000000402"),
                            MaxStockingDensity = 30f,
                            SpeciesId = new Guid("aaaaaaaa-0000-0000-0000-000000000101")
                        });
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.SpeciesThreshold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("GrowthStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("growth_stage_id");

                    b.Property<float>("MaxValue")
                        .HasColumnType("real")
                        .HasColumnName("max_value");

                    b.Property<float>("MinValue")
                        .HasColumnType("real")
                        .HasColumnName("min_value");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("SensorTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_type_id");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.HasKey("Id")
                        .HasName("pk_species_thresholds");

                    b.HasIndex("GrowthStageId")
                        .HasDatabaseName("ix_species_thresholds_growth_stage_id");

                    b.HasIndex("SensorTypeId")
                        .HasDatabaseName("ix_species_thresholds_sensor_type_id");

                    b.HasIndex("SpeciesId", "GrowthStageId", "SensorTypeId")
                        .IsUnique()
                        .HasDatabaseName("ix_species_thresholds_species_id_growth_stage_id_sensor_type_id");

                    b.ToTable("species_thresholds", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_name");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@example.com",
                            FirstName = "",
                            IsDeleted = false,
                            IsVerified = true,
                            LastName = "",
                            PasswordHash = "$2a$11$TjsTmXlpjjTVPajZiLxCV.XPuTPgCgphg7sfC9Fs/YwSA4M4IYqYu",
                            RoleId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user@example.com",
                            FirstName = "",
                            IsDeleted = false,
                            IsVerified = true,
                            LastName = "",
                            PasswordHash = "$2a$11$TjsTmXlpjjTVPajZiLxCV.XPuTPgCgphg7sfC9Fs/YwSA4M4IYqYu",
                            RoleId = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.UserFarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_farms");

                    b.HasIndex("FarmId")
                        .HasDatabaseName("ix_user_farms_farm_id");

                    b.HasIndex("UserId", "FarmId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_farms_user_id_farm_id");

                    b.ToTable("user_farms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-0001-0001-0001-000000000001"),
                            FarmId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            UserId = new Guid("aaaaaaaa-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Verification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_date");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_consumed");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_verifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_verifications_user_id");

                    b.HasIndex("IsConsumed", "ExpireDate")
                        .HasDatabaseName("ix_verifications_is_consumed_expire_date");

                    b.ToTable("verifications", (string)null);
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Alert", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.FarmingBatch", "FarmingBatch")
                        .WithMany("Alerts")
                        .HasForeignKey("FarmingBatchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_alerts_farming_batches_farming_batch_id");

                    b.HasOne("IRasRag.Domain.Entities.FishTank", "FishTank")
                        .WithMany("Alerts")
                        .HasForeignKey("FishTankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_fish_tanks_fish_tank_id");

                    b.HasOne("IRasRag.Domain.Entities.SensorLog", "SensorLog")
                        .WithMany("Alerts")
                        .HasForeignKey("SensorLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_sensor_logs_sensor_log_id");

                    b.HasOne("IRasRag.Domain.Entities.SensorType", "SensorType")
                        .WithMany("Alerts")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_sensor_types_sensor_type_id");

                    b.HasOne("IRasRag.Domain.Entities.SpeciesThreshold", "SpeciesThreshold")
                        .WithMany("Alerts")
                        .HasForeignKey("SpeciesThresholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_species_thresholds_species_threshold_id");

                    b.Navigation("FarmingBatch");

                    b.Navigation("FishTank");

                    b.Navigation("SensorLog");

                    b.Navigation("SensorType");

                    b.Navigation("SpeciesThreshold");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Camera", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.Farm", "Farm")
                        .WithMany("Cameras")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cameras_farms_farm_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.ControlDevice", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.ControlDeviceType", "ControlDeviceType")
                        .WithMany("ControlDevices")
                        .HasForeignKey("ControlDeviceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_control_devices_control_device_types_control_device_type_id");

                    b.HasOne("IRasRag.Domain.Entities.MasterBoard", "MasterBoard")
                        .WithMany("ControlDevices")
                        .HasForeignKey("MasterBoardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_control_devices_master_boards_master_board_id");

                    b.Navigation("ControlDeviceType");

                    b.Navigation("MasterBoard");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.CorrectiveAction", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.Alert", "Alert")
                        .WithMany("CorrectiveActions")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_corrective_actions_alerts_alert_id");

                    b.HasOne("IRasRag.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_corrective_actions_users_user_id");

                    b.Navigation("Alert");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Document", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documents_users_uploaded_by_user_id");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.FarmingBatch", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.FishTank", "FishTank")
                        .WithMany("FarmingBatches")
                        .HasForeignKey("FishTankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_farming_batches_fish_tanks_fish_tank_id");

                    b.HasOne("IRasRag.Domain.Entities.Species", "Species")
                        .WithMany("FarmingBatches")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_farming_batches_species_species_id");

                    b.Navigation("FishTank");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.FeedingLog", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.FarmingBatch", "FarmingBatch")
                        .WithMany("FeedingLogs")
                        .HasForeignKey("FarmingBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feeding_logs_farming_batches_farming_batch_id");

                    b.Navigation("FarmingBatch");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.FishTank", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.Farm", "Farm")
                        .WithMany("FishTanks")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fish_tanks_farms_farm_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Job", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.JobType", "JobType")
                        .WithMany("Jobs")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_job_types_job_type_id");

                    b.HasOne("IRasRag.Domain.Entities.Sensor", "Sensor")
                        .WithMany("Jobs")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_jobs_sensors_sensor_id");

                    b.Navigation("JobType");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.JobControlMapping", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.ControlDevice", "ControlDevice")
                        .WithMany("JobControlMappings")
                        .HasForeignKey("ControlDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_control_mappings_control_devices_control_device_id");

                    b.HasOne("IRasRag.Domain.Entities.Job", "Job")
                        .WithMany("JobControlMappings")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_control_mappings_jobs_job_id");

                    b.Navigation("ControlDevice");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.MasterBoard", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.FishTank", "FishTank")
                        .WithMany("MasterBoards")
                        .HasForeignKey("FishTankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_master_boards_fish_tanks_fish_tank_id");

                    b.Navigation("FishTank");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.MortalityLog", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.FarmingBatch", "Batch")
                        .WithMany("MortalityLogs")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mortality_logs_farming_batches_batch_id");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.Alert", "Alert")
                        .WithMany("Recommendations")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recommendations_alerts_alert_id");

                    b.HasOne("IRasRag.Domain.Entities.Document", "Document")
                        .WithMany("Recommendations")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recommendations_documents_document_id");

                    b.Navigation("Alert");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Sensor", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.MasterBoard", "MasterBoard")
                        .WithMany("Sensors")
                        .HasForeignKey("MasterBoardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_master_boards_master_board_id");

                    b.HasOne("IRasRag.Domain.Entities.SensorType", "SensorType")
                        .WithMany("Sensors")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_sensor_types_sensor_type_id");

                    b.Navigation("MasterBoard");

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.SensorLog", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.Sensor", "Sensor")
                        .WithMany("SensorLogs")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_logs_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.SpeciesStageConfig", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.FeedType", "FeedType")
                        .WithMany("SpeciesStageConfigs")
                        .HasForeignKey("FeedTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_species_stage_configs_feed_types_feed_type_id");

                    b.HasOne("IRasRag.Domain.Entities.GrowthStage", "GrowthStage")
                        .WithMany("SpeciesStageConfigs")
                        .HasForeignKey("GrowthStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_species_stage_configs_growth_stages_growth_stage_id");

                    b.HasOne("IRasRag.Domain.Entities.Species", "Species")
                        .WithMany("SpeciesStageConfigs")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_species_stage_configs_species_species_id");

                    b.Navigation("FeedType");

                    b.Navigation("GrowthStage");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.SpeciesThreshold", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.GrowthStage", "GrowthStage")
                        .WithMany("SpeciesThresholds")
                        .HasForeignKey("GrowthStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_species_thresholds_growth_stages_growth_stage_id");

                    b.HasOne("IRasRag.Domain.Entities.SensorType", "SensorType")
                        .WithMany("SpeciesThresholds")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_species_thresholds_sensor_types_sensor_type_id");

                    b.HasOne("IRasRag.Domain.Entities.Species", "Species")
                        .WithMany("SpeciesThresholds")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_species_thresholds_species_species_id");

                    b.Navigation("GrowthStage");

                    b.Navigation("SensorType");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.User", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.UserFarm", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.Farm", "Farm")
                        .WithMany("UserFarms")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_farms_farms_farm_id");

                    b.HasOne("IRasRag.Domain.Entities.User", "User")
                        .WithMany("UserFarms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_farms_users_user_id");

                    b.Navigation("Farm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Verification", b =>
                {
                    b.HasOne("IRasRag.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Alert", b =>
                {
                    b.Navigation("CorrectiveActions");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.ControlDevice", b =>
                {
                    b.Navigation("JobControlMappings");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.ControlDeviceType", b =>
                {
                    b.Navigation("ControlDevices");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Document", b =>
                {
                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Farm", b =>
                {
                    b.Navigation("Cameras");

                    b.Navigation("FishTanks");

                    b.Navigation("UserFarms");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.FarmingBatch", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("FeedingLogs");

                    b.Navigation("MortalityLogs");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.FeedType", b =>
                {
                    b.Navigation("SpeciesStageConfigs");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.FishTank", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("FarmingBatches");

                    b.Navigation("MasterBoards");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.GrowthStage", b =>
                {
                    b.Navigation("SpeciesStageConfigs");

                    b.Navigation("SpeciesThresholds");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Job", b =>
                {
                    b.Navigation("JobControlMappings");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.JobType", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.MasterBoard", b =>
                {
                    b.Navigation("ControlDevices");

                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Sensor", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("SensorLogs");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.SensorLog", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.SensorType", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Sensors");

                    b.Navigation("SpeciesThresholds");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.Species", b =>
                {
                    b.Navigation("FarmingBatches");

                    b.Navigation("SpeciesStageConfigs");

                    b.Navigation("SpeciesThresholds");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.SpeciesThreshold", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("IRasRag.Domain.Entities.User", b =>
                {
                    b.Navigation("UserFarms");
                });
#pragma warning restore 612, 618
        }
    }
}
